import type { ExecutionTicket } from "./execution";

export const EXECUTION_TICKET_FIXTURE = {
  plan: {
    schema_version: "1.0",
    plan_id: "plan-1",
    plan_hash: "a".repeat(64),
    idempotency_key: "idem-1",
    session_id: "live",
    signal_id: "signal-1",
    broker_id: "ibkr",
    strategy: "LongGamma",
    execution_mode: "PAPER",
    created_at_utc: "2099-07-21T14:30:00Z",
    legs: [{ side: "BUY", type: "CALL", contract_id: "QQQ-20990721-C-500", expiry: "2099-07-21", strike: "500", quantity: 1 }],
    limit_price: "2.50",
    max_loss: "250.00",
    expires_at_utc: "2099-07-21T14:31:00Z",
    rule_version: "rules-p3",
    data_snapshot_ids: ["mkt-1", "opt-1"],
    manual_confirmation_required: true,
  },
  order: {
    schema_version: "1.0",
    order_id: "order-1",
    plan_id: "plan-1",
    plan_hash: "a".repeat(64),
    idempotency_key: "idem-1",
    session_id: "live",
    broker_id: "ibkr",
    execution_mode: "PAPER",
    state: "AWAITING_CONFIRMATION",
    total_quantity: 1,
    filled_quantity: 0,
    broker_order_id: null,
    expires_at_utc: "2099-07-21T14:31:00Z",
    updated_at_utc: "2099-07-21T14:30:01Z",
    state_version: 1,
    risk_reason_codes: [],
  },
} satisfies ExecutionTicket;
