#!/usr/bin/env bash
# Generate Python gRPC stubs from the shared proto into app/grpc_gen/.
# Output is git-ignored and regenerated here (contracts first — CLAUDE.md 4).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
API_DIR="$ROOT/services/application-api"
PROTO_DIR="$ROOT/packages/contracts/proto"
OUT="$API_DIR/app/grpc_gen"

mkdir -p "$OUT"

cd "$API_DIR"
uv run python -m grpc_tools.protoc \
  -I "$PROTO_DIR" \
  --python_out="$OUT" \
  --grpc_python_out="$OUT" \
  --pyi_out="$OUT" \
  "$PROTO_DIR/market.proto"

# grpc_tools emits a top-level `import market_pb2`; rewrite to a package-relative
# import so the stubs work as `app.grpc_gen.*` without polluting sys.path.
GRPC_FILE="$OUT/market_pb2_grpc.py"
if [[ "$(uname)" == "Darwin" ]]; then
  sed -i '' 's/^import market_pb2 as market__pb2/from . import market_pb2 as market__pb2/' "$GRPC_FILE"
else
  sed -i 's/^import market_pb2 as market__pb2/from . import market_pb2 as market__pb2/' "$GRPC_FILE"
fi

cat > "$OUT/__init__.py" <<'PY'
"""Generated gRPC stubs for the Python<->Rust market boundary.

Do not edit — regenerated by scripts/gen_python_grpc.sh from
packages/contracts/proto/market.proto. Git-ignored; run `make contracts`.
"""
from app.grpc_gen import market_pb2, market_pb2_grpc

__all__ = ["market_pb2", "market_pb2_grpc"]
PY

echo "Python gRPC stubs generated at app/grpc_gen/"
