#!/usr/bin/env bash
# Generate Python gRPC stubs from the shared proto into app/grpc_gen/.
# Output is git-ignored and regenerated here (contracts first — CLAUDE.md 4).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
API_DIR="$ROOT/services/application-api"
PROTO_DIR="$ROOT/packages/contracts/proto"
OUT="$API_DIR/app/grpc_gen"

mkdir -p "$OUT"

cd "$API_DIR"
uv run python -m grpc_tools.protoc \
  -I "$PROTO_DIR" \
  --python_out="$OUT" \
  --grpc_python_out="$OUT" \
  --pyi_out="$OUT" \
  "$PROTO_DIR/market.proto" \
  "$PROTO_DIR/execution.proto" \
  "$PROTO_DIR/broker.proto"

# grpc_tools emits a top-level `import market_pb2`; rewrite to a package-relative
# import so the stubs work as `app.grpc_gen.*` without polluting sys.path.
for GRPC_FILE in \
  "$OUT/market_pb2_grpc.py" \
  "$OUT/execution_pb2_grpc.py" \
  "$OUT/broker_pb2.py" \
  "$OUT/broker_pb2_grpc.py"; do
  if [[ "$(uname)" == "Darwin" ]]; then
    sed -i '' -E 's/^import ([a-z_]+_pb2) as /from . import \1 as /' "$GRPC_FILE"
  else
    sed -i -E 's/^import ([a-z_]+_pb2) as /from . import \1 as /' "$GRPC_FILE"
  fi
done

cat > "$OUT/__init__.py" <<'PY'
"""Generated gRPC stubs for the Python<->Rust service boundaries.

Do not edit — regenerated by scripts/gen_python_grpc.sh from
packages/contracts/proto/*.proto. Git-ignored; run `make contracts`.
"""
from app.grpc_gen import (
    broker_pb2,
    broker_pb2_grpc,
    execution_pb2,
    execution_pb2_grpc,
    market_pb2,
    market_pb2_grpc,
)

__all__ = [
    "broker_pb2",
    "broker_pb2_grpc",
    "execution_pb2",
    "execution_pb2_grpc",
    "market_pb2",
    "market_pb2_grpc",
]
PY

echo "Python gRPC stubs generated at app/grpc_gen/"
